# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v lantern-msd

    - name: Test
      run: go test -v lantern-msd/test

    - name: Test Download
      run: ./lantern-msd --url https://nodejs.org/dist/v21.7.3/node-v21.7.3-linux-x64.tar.xz -k 1048576 -s 23
